version: '3.8'

services:
  app:
    build: .
    volumes:
      - backend_node_modules:/app/backend/node_modules
      - frontend_node_modules:/app/frontend/node_modules
      - backend_ssl:/app/backend
    ports:
      - '3000:3000'
      - '5173:5173'
    environment:
      - NODE_ENV=production
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}

volumes:
  backend_node_modules:
  frontend_node_modules:
  backend_ssl:
